spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers,beans,threaddump

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
